FROM node:20-alpine AS build
WORKDIR /app
COPY 16_SISTEMAS/FORJA_OS_PLATFORM/package*.json ./
RUN npm install
COPY 16_SISTEMAS/FORJA_OS_PLATFORM .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
